Well, Poirot? Murder or suicide?"
                *   "Murder!"
                    "And who did it?"
                    * *     "Detective-Inspector Japp!"
                    * *     "Captain Hastings!"
                    * *     "Myself!"
                    - -     "You must be joking!"
                    * *     "Mon ami, I am deadly serious."
                    * *     "If only..."
                *   "Suicide!"
                    "Really, Poirot? Are you quite sure?"
                    * *     "Quite sure."
                    * *     "It is perfectly obvious."
                -   Mrs. Christie lowered her manuscript a moment. The rest of the writing group sat, open-mouthed.